- name: create ec2 and r53 records
  hosts: localhost
  vars:
    zone: db.nagacharan.site
    instances:
    - db
    - backend
    - frontend
  tasks: 
  - name: create ec2-instance
    amazon.aws.ec2_instance:
      instance_type: t2.micro
      name: "{{ item }}"
      security_group: allow-everything #replace 
      image_id: ami-090252cbe067a9e58
      tags:
        name: "{{ item }}"

  loop:
  - "{{ instances }}"
  register: ec2_instances_info

- name: print output
  ansible.builtin.debug:
    msg: "Output: {{ ec2_instance_info }}"

- name: create r53 records
  amazon.aws.route53:
    state: present 
    zone: "{{ zone }}"
    record: "{{ item }}.{{ zone }}"
    type: A
    value: "{{ item.private_ip_address }}"
    override: true
    ttl: 1
  loop: "{{ ec2_instances_info.results.instances }}"